# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/browser-testing/
# https://stackoverflow.com/questions/22022319/selenium-testing-with-circleci
version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo "export SHOPIFY_CHECK_INSTA=$SHOPIFY_CHECK_INSTA" >> $BASH_ENV
      - run:
          name: Setup Dependencies
          command: |
            pip install selenium PyYAML
      - run:
          name: Test
          command: python -m unittest
workflows:
  main:
    jobs:
      - build
